micronaut:
  application:
    name: eventorganizer
  security:
    enabled: true
    intercept-url-map:
      - pattern: /**
        access:
          - isAuthenticated()
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    oauth2:
      clients:
        keycloak:
          client-id: ""
          client-secret: ""
          client-credentials:
            service-id-regex: "keycloak"
          token:
            url: ""
            auth-method: client_secret_basic
  caches:
    my-cache:
      maximumSize: 20

jackson:
  bean-introspection-module: true
  serialization-inclusion: always

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/eventorg
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
