micronaut:
  application:
    name: eventorganizer
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    enabled: true
    ip-patterns: []
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      enabled: true
      roles-name: "roles"
      jwt:
        enabled: true
        signatures:
          jwks:
            auth0:
              url: "https://eventorg.eu.auth0.com//.well-known/jwks.json"
  caches:
    my-cache:
      maximumSize: 20

jackson:
  bean-introspection-module: true
  serialization-inclusion: always

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/eventorg
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
